appId: dev.ipf.whitenoise.android.maestrolab
name: settings-profile-keys
---
- assertVisible: "Maestro group"
- tapOn: "Open settings.*"
- assertVisible: "Settings"
- tapOn: "Profile Keys"
- assertVisible: "Show private key"
- assertVisible: "Private key hidden"
- back
- assertVisible: "Settings"
