package dev.ipf.whitenoise.android.core

import dev.ipf.whitenoise.android.BuildConfig
import java.net.URI

data class ProfileLink(
    val npub: String,
) {
    init {
        require(isLikelyNpub(npub)) { "invalid npub" }
    }

    val uri: String = "${BuildConfig.WHITENOISE_DEEP_LINK_SCHEME}://profile/$npub"

    companion object {
        // A Nostr npub is bech32-encoded: prefix `npub1`, body in the bech32
        // alphabet (lowercase a-z 0-9 minus 'b' 'i' 'o' '1'), total length 63.
        // We don't bech32-decode here (that's the FFI's job) — we just reject
        // clearly-invalid inputs so ProfileSheet doesn't open against garbage.
        private const val NPUB_LENGTH = 63
        private val NPUB_BODY_CHARSET = Regex("^[ac-hj-np-z02-9]+$")

        private fun isLikelyNpub(value: String): Boolean {
            if (value.length != NPUB_LENGTH) return false
            if (!value.startsWith("npub1")) return false
            return NPUB_BODY_CHARSET.matches(value.substring(5))
        }

        fun parse(raw: String): ProfileLink? {
            val trimmed = raw.trim()
            if (trimmed.isEmpty()) return null

            parseUri(trimmed)?.let { return it }

            if (trimmed.lowercase().startsWith("nostr:")) {
                val rest = trimmed.drop("nostr:".length)
                if (isLikelyNpub(rest)) return ProfileLink(rest)
            }
            if (isLikelyNpub(trimmed)) return ProfileLink(trimmed)
            return null
        }

        private fun parseUri(raw: String): ProfileLink? {
            val uri = runCatching { URI(raw) }.getOrNull() ?: return null
            if (uri.scheme?.lowercase() !in PROFILE_SCHEMES) return null

            if (uri.isOpaque) {
                // Opaque form `scheme:profile/npub…` (no `//`): the payload lives
                // in schemeSpecificPart, so host/path are both null. Our generator
                // only ever emits the hierarchical `://` form, so this branch only
                // matters for externally-authored pasted links (#847).
                val ssp =
                    uri.schemeSpecificPart
                        .orEmpty()
                        .trim('/')
                        .removePrefix("profile/")
                        .trim('/')
                return if (isLikelyNpub(ssp)) ProfileLink(ssp) else null
            }

            val host = uri.host.orEmpty()
            val path = uri.path.orEmpty().trim('/')
            return when {
                host.equals("profile", ignoreCase = true) && isLikelyNpub(path) -> ProfileLink(path)
                isLikelyNpub(host) -> ProfileLink(host)
                else -> null
            }
        }

        // Accept every known flavor scheme so a link generated by one build still
        // resolves when pasted into another, and always include this build's own
        // BuildConfig scheme so link generation and parsing can never silently
        // drift apart if a future flavor adds a scheme (#847).
        private val PROFILE_SCHEMES =
            setOf(
                "whitenoise",
                "whitenoise-staging",
                "whitenoise-dev",
                BuildConfig.WHITENOISE_DEEP_LINK_SCHEME.lowercase(),
            )
    }
}
