package dev.ipf.whitenoise.android.ui.group

import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

class GroupEmojiImageWiringTest {
    @Test
    fun newGroupUsesGeneratedDraftForPreviewAndInitialEncryptedImage() {
        val source = source("ui/chats/newchat/NewGroupSetupScreen.kt").readText()

        assertTrue("new-group image chooser must expose emoji generation", "onPickEmoji =" in source)
        assertTrue("new-group flow must render the shared emoji sheet", "GroupEmojiImagePickerSheet(" in source)
        assertTrue("generated bytes must become the previewed draft", "imageDraft = draft" in source)
        assertTrue("the same draft must reach the existing MDK image contract", "imageDraft?.initialGroupImage()" in source)
    }

    @Test
    fun groupInfoUsesExistingEncryptedImageMutation() {
        val source = source("ui/group/GroupEditScreen.kt").readText()

        assertTrue("group-info image chooser must expose emoji generation", "onPickEmoji =" in source)
        assertTrue("group-info flow must render the shared emoji sheet", "GroupEmojiImagePickerSheet(" in source)
        assertTrue("generated bytes must use the existing image mutation", "onApply = { draft -> updateImage { draft } }" in source)
        assertTrue("the existing controller API remains authoritative", "controller.updateGroupImage(draft)" in source)
    }

    private fun source(relativePath: String): File =
        listOf(
            File("app/src/main/java/dev/ipf/whitenoise/android/$relativePath"),
            File("src/main/java/dev/ipf/whitenoise/android/$relativePath"),
        ).firstOrNull(File::isFile) ?: error("Missing source: $relativePath")
}
