package dev.ipf.whitenoise.android.state

import androidx.test.platform.app.InstrumentationRegistry
import dev.ipf.marmotkit.Marmot
import dev.ipf.marmotkit.MarmotAndroid
import dev.ipf.marmotkit.MarmotKitException
import dev.ipf.marmotkit.MarmotOptions
import dev.ipf.marmotkit.RelayPolicyFfi
import dev.ipf.marmotkit.verifyPublicNostrEventJson
import dev.ipf.whitenoise.android.ManualDeviceFixture
import kotlinx.coroutines.CancellationException
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import kotlinx.coroutines.withTimeout
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Assume.assumeTrue
import org.junit.Test
import java.io.File
import java.util.UUID

/** Opt-in fresh signed MLS vectors generated by the pinned MDK's own legacy/expiry/component builders. */
@ManualDeviceFixture
class SignedInvitationVectorDeviceTest {
    /** Real wire signatures cannot turn invalid, legacy, expired or incompatible recipients into group members. */
    @Test fun signedPackageRejectionsPreserveCreateAndInviteState() =
        runBlocking {
            assumeTrue(InstrumentationRegistry.getArguments().getString("signedInvitationE2e") == "true")
            val context = InstrumentationRegistry.getInstrumentation().targetContext
            MarmotAndroid.initialize(context)
            val fixture = JSONObject(File(context.cacheDir, "pr3201-signed-vectors.json").readText())
            check(fixture.getString("mdk") == "d4e91c8d90293de1a664a950a134f747dbb197a8")
            check(System.currentTimeMillis() / 1000L - fixture.getLong("generatedAt") in 0..3600L) {
                "Generate fresh vectors; stale MLS lifetimes cannot qualify this matrix"
            }
            val root = File(context.cacheDir, "signed-vectors-${UUID.randomUUID()}").apply { mkdirs() }
            try {
                withTimeout(120_000L) {
                    while (System.currentTimeMillis() / 1000L <= fixture.getLong("expiredAfter")) delay(100L)
                    LoopbackNostrRelay(DISCOVERY_PORT).use { discovery ->
                        LoopbackNostrRelay(OUTBOX_PORT).use { outbox ->
                            verifyCases(root, fixture.getJSONArray("cases"), discovery, outbox)
                        }
                    }
                }
            } finally {
                check(root.deleteRecursively())
            }
        }

    /** Seeds only independently verified public wire events and creates a fresh inviter for the matrix. */
    private suspend fun verifyCases(
        root: File,
        cases: JSONArray,
        discovery: LoopbackNostrRelay,
        outbox: LoopbackNostrRelay,
    ) {
        for (index in 0 until cases.length()) {
            val case = cases.getJSONObject(index)
            val routes = case.getJSONArray("relays").objects()
            val packages = case.getJSONArray("packages").objects()
            (routes + packages).forEach { assertTrue(verifyPublicNostrEventJson(it.toString())) }
            discovery.seedEvents(routes + packages.take(1))
            outbox.seedEvents(routes + if (case.getString("name") == "replacement") packages.drop(1) else emptyList())
        }
        val relays = listOf(discovery.url)
        val native =
            Marmot.newWithConfiguration(
                root.path,
                relays,
                MarmotOptions(relayPolicy = RelayPolicyFfi.ALLOW_LOOPBACK_RELAYS_AND_BLOBS),
            )
        try {
            native.start()
            val account = native.createIdentity(relays, relays).accountIdHex
            val group = native.createGroup(account, "Signed vector fixture", emptyList(), null)
            for (index in 0 until cases.length()) verifyRejected(native, account, group, cases.getJSONObject(index))
            assertTrue(discovery.publicationAttempts(GIFT_WRAP).isEmpty())
            assertTrue(outbox.publicationAttempts(GIFT_WRAP).isEmpty())
        } finally {
            native.shutdownAndClose()
        }
    }

    /** Both commands must fail before creating a chat, advancing an epoch or publishing a Welcome. */
    private suspend fun verifyRejected(
        native: Marmot,
        account: String,
        group: String,
        case: JSONObject,
    ) {
        val peer = case.getString("account")
        val epoch = native.groupMlsState(account, group).epoch
        val chats = native.chatList(account, true).map { it.groupIdHex }.toSet()
        rejected(case.getString("name")) { native.inviteMembersDetailed(account, group, listOf(peer)) }
        rejected(case.getString("name")) { native.createGroup(account, "Unsafe package", listOf(peer), null) }
        assertEquals(1, native.groupMembers(account, group).size)
        assertEquals(epoch, native.groupMlsState(account, group).epoch)
        assertEquals(chats, native.chatList(account, true).map { it.groupIdHex }.toSet())
    }

    /** A package rejection is distinct from an unrelated missing-inbox or transport failure. */
    private suspend fun rejected(
        name: String,
        block: suspend () -> Unit,
    ) {
        val error =
            try {
                block()
                null
            } catch (cancel: CancellationException) {
                throw cancel
            } catch (failure: Exception) {
                failure
            }
        val packageFailure =
            error is MarmotKitException.InvalidKeyPackageEvent ||
                (
                    name == "incompatible" &&
                        error is MarmotKitException.Runtime &&
                        error.message.orEmpty().contains("missing required capabilities")
                )
        assertTrue("$name must fail package preflight: $error", packageFailure)
    }

    /** Copies the JSON fixture's record list without changing signed fields. */
    private fun JSONArray.objects(): List<JSONObject> = (0 until length()).map(::getJSONObject)

    private companion object {
        const val DISCOVERY_PORT = 44111
        const val OUTBOX_PORT = 44112
        const val GIFT_WRAP = 1059
    }
}
